[package]
name = "mesh-routing"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "MeshRustic routing core (static pools, unified Router)"

[dependencies]
mesh-crypto = { path = "../mesh-crypto" }
mesh-protocol = { path = "../mesh-protocol" }
mesh-radio = { path = "../mesh-radio" }
mesh-store = { path = "../mesh-store", default-features = false }
heapless = "0.8"

[features]
default = ["pki"]
std = []
pki = ["mesh-crypto/pki", "mesh-store/pki"]

[dev-dependencies]
static_cell = "2"
